--
-- PostgreSQL database dump
--

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', 'public', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_media (
    booking_media_id integer NOT NULL,
    booking_media_type character varying(20),
    booking_media_media_path character varying(100),
    booking_media_is_deleted boolean NOT NULL,
    booking_media_created_at timestamp with time zone NOT NULL,
    booking_media_updated_at timestamp with time zone NOT NULL,
    booking_media_bookings_id integer
);


--
-- Name: booking_media_booking_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_media ALTER COLUMN booking_media_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_media_booking_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    bookings_id integer NOT NULL,
    bookings_date date,
    bookings_time time without time zone,
    bookings_notes text,
    bookings_status character varying(20) NOT NULL,
    bookings_created_at timestamp with time zone NOT NULL,
    bookings_updated_at timestamp with time zone NOT NULL,
    bookings_car_cleaner_id integer,
    bookings_users_id integer,
    bookings_wash_deducted boolean NOT NULL,
    bookings_reminder_sent boolean NOT NULL
);


--
-- Name: bookings_bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN bookings_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_day_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_day_preferences (
    customer_day_preferences_id integer NOT NULL,
    customer_day_preferences_days jsonb,
    customer_day_preferences_time time without time zone,
    customer_day_preferences_is_deleted boolean CONSTRAINT customer_day_preferences_customer_day_preferences_is_d_not_null NOT NULL,
    customer_day_preferences_created_at timestamp with time zone CONSTRAINT customer_day_preferences_customer_day_preferences_crea_not_null NOT NULL,
    customer_day_preferences_updated_at timestamp with time zone CONSTRAINT customer_day_preferences_customer_day_preferences_upda_not_null NOT NULL,
    customer_day_preferences_plans_id integer,
    customer_day_preferences_users_id integer
);


--
-- Name: customer_day_preferences_customer_day_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_day_preferences ALTER COLUMN customer_day_preferences_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_day_preferences_customer_day_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    plans_id integer NOT NULL,
    plans_name character varying(255),
    plans_sale_price numeric(15,2),
    plans_discount_price numeric(15,2),
    plans_car_wash_allowed integer,
    plans_payment_link character varying(255),
    plans_service_include text,
    plans_car_allowed character varying(20) NOT NULL,
    plans_billing_frequency character varying(20) NOT NULL,
    plans_is_active boolean NOT NULL,
    plans_is_deleted boolean NOT NULL,
    plans_created_at timestamp with time zone NOT NULL,
    plans_updated_at timestamp with time zone NOT NULL
);


--
-- Name: plans_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plans ALTER COLUMN plans_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    roles_id integer NOT NULL,
    roles_keys character varying(50),
    roles_name character varying(255),
    roles_is_active boolean NOT NULL,
    roles_is_deleted boolean NOT NULL,
    roles_created_at timestamp with time zone NOT NULL,
    roles_updated_at timestamp with time zone NOT NULL
);


--
-- Name: roles_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN roles_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_areas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_areas (
    service_areas_id integer NOT NULL,
    service_areas_name character varying(255) NOT NULL,
    service_areas_pincode character varying(10) NOT NULL,
    service_areas_is_active boolean NOT NULL,
    service_areas_is_deleted boolean NOT NULL,
    service_areas_created_at timestamp with time zone NOT NULL,
    service_areas_updated_at timestamp with time zone NOT NULL
);


--
-- Name: service_areas_service_areas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_areas ALTER COLUMN service_areas_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_areas_service_areas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_plan_mapping_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_plan_mapping_logs (
    user_plan_mapping_logs_id integer NOT NULL,
    user_plan_mapping_logs_action character varying(20),
    user_plan_mapping_logs_notes text,
    user_plan_mapping_logs_created_at timestamp with time zone CONSTRAINT user_plan_mapping_logs_user_plan_mapping_logs_created__not_null NOT NULL,
    user_plan_mapping_logs_plans_id integer,
    user_plan_mapping_logs_user_plan_mappings_id integer
);


--
-- Name: user_plan_mapping_logs_user_plan_mapping_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_plan_mapping_logs ALTER COLUMN user_plan_mapping_logs_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_plan_mapping_logs_user_plan_mapping_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_plan_mappings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_plan_mappings (
    user_plan_mappings_id integer NOT NULL,
    user_plan_mappings_car_wash_left integer,
    user_plan_mappings_plans_id integer,
    user_plan_mappings_users_id integer
);


--
-- Name: user_plan_mappings_user_plan_mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_plan_mappings ALTER COLUMN user_plan_mappings_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_plan_mappings_user_plan_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    users_id integer NOT NULL,
    users_first_name character varying(255),
    users_middle_name character varying(255),
    users_last_name character varying(255),
    users_profile_picture character varying(100),
    users_landmark character varying(255),
    users_password text,
    users_email character varying(255),
    users_phone_number character varying(20),
    users_alternate_phone_number character varying(20),
    users_whatsapp_number character varying(20),
    users_address_line_1 text,
    users_address_line_2 text,
    users_city character varying(255),
    users_state character varying(255),
    users_country character varying(255),
    users_postcode character varying(20),
    users_is_active boolean NOT NULL,
    users_is_deleted boolean NOT NULL,
    users_created_at timestamp with time zone NOT NULL,
    users_updated_at timestamp with time zone NOT NULL,
    users_preferred_cleaner_id_id integer,
    users_roles_keys character varying(50),
    users_service_area_id integer
);


--
-- Name: users_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN users_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: booking_media booking_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_media
    ADD CONSTRAINT booking_media_pkey PRIMARY KEY (booking_media_id);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (bookings_id);


--
-- Name: customer_day_preferences customer_day_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_day_preferences
    ADD CONSTRAINT customer_day_preferences_pkey PRIMARY KEY (customer_day_preferences_id);


--
-- Name: plans plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (plans_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (roles_id);


--
-- Name: roles roles_roles_keys_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_roles_keys_key UNIQUE (roles_keys);


--
-- Name: service_areas service_areas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_areas
    ADD CONSTRAINT service_areas_pkey PRIMARY KEY (service_areas_id);


--
-- Name: service_areas service_areas_service_areas_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_areas
    ADD CONSTRAINT service_areas_service_areas_name_key UNIQUE (service_areas_name);


--
-- Name: user_plan_mapping_logs user_plan_mapping_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_plan_mapping_logs
    ADD CONSTRAINT user_plan_mapping_logs_pkey PRIMARY KEY (user_plan_mapping_logs_id);


--
-- Name: user_plan_mappings user_plan_mappings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_plan_mappings
    ADD CONSTRAINT user_plan_mappings_pkey PRIMARY KEY (user_plan_mappings_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (users_id);


--
-- Name: users users_users_alternate_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_users_alternate_phone_number_key UNIQUE (users_alternate_phone_number);


--
-- Name: users users_users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_users_email_key UNIQUE (users_email);


--
-- Name: users users_users_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_users_phone_number_key UNIQUE (users_phone_number);


--
-- Name: users users_users_whatsapp_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_users_whatsapp_number_key UNIQUE (users_whatsapp_number);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: booking_media_booking_media_bookings_id_c9f1d7d7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX booking_media_booking_media_bookings_id_c9f1d7d7 ON public.booking_media USING btree (booking_media_bookings_id);


--
-- Name: bookings_bookings_car_cleaner_id_0ab62342; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookings_bookings_car_cleaner_id_0ab62342 ON public.bookings USING btree (bookings_car_cleaner_id);


--
-- Name: bookings_bookings_users_id_4df94e92; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookings_bookings_users_id_4df94e92 ON public.bookings USING btree (bookings_users_id);


--
-- Name: customer_day_preferences_customer_day_preferences_p_100ce6d3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_day_preferences_customer_day_preferences_p_100ce6d3 ON public.customer_day_preferences USING btree (customer_day_preferences_plans_id);


--
-- Name: customer_day_preferences_customer_day_preferences_u_29d05c4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX customer_day_preferences_customer_day_preferences_u_29d05c4b ON public.customer_day_preferences USING btree (customer_day_preferences_users_id);


--
-- Name: roles_roles_keys_6cea4b64_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX roles_roles_keys_6cea4b64_like ON public.roles USING btree (roles_keys varchar_pattern_ops);


--
-- Name: service_areas_service_areas_name_cda7c55a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX service_areas_service_areas_name_cda7c55a_like ON public.service_areas USING btree (service_areas_name varchar_pattern_ops);


--
-- Name: user_plan_mapping_logs_user_plan_mapping_logs_plans_id_e47c2570; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_plan_mapping_logs_user_plan_mapping_logs_plans_id_e47c2570 ON public.user_plan_mapping_logs USING btree (user_plan_mapping_logs_plans_id);


--
-- Name: user_plan_mapping_logs_user_plan_mapping_logs_use_6cd3d78a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_plan_mapping_logs_user_plan_mapping_logs_use_6cd3d78a ON public.user_plan_mapping_logs USING btree (user_plan_mapping_logs_user_plan_mappings_id);


--
-- Name: user_plan_mappings_user_plan_mappings_plans_id_bcaf51da; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_plan_mappings_user_plan_mappings_plans_id_bcaf51da ON public.user_plan_mappings USING btree (user_plan_mappings_plans_id);


--
-- Name: user_plan_mappings_user_plan_mappings_users_id_5423ff41; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_plan_mappings_user_plan_mappings_users_id_5423ff41 ON public.user_plan_mappings USING btree (user_plan_mappings_users_id);


--
-- Name: users_users_alternate_phone_number_bfeaf778_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_alternate_phone_number_bfeaf778_like ON public.users USING btree (users_alternate_phone_number varchar_pattern_ops);


--
-- Name: users_users_email_e6659159_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_email_e6659159_like ON public.users USING btree (users_email varchar_pattern_ops);


--
-- Name: users_users_phone_number_3dcbfc54_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_phone_number_3dcbfc54_like ON public.users USING btree (users_phone_number varchar_pattern_ops);


--
-- Name: users_users_preferred_cleaner_id_id_c96cecbc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_preferred_cleaner_id_id_c96cecbc ON public.users USING btree (users_preferred_cleaner_id_id);


--
-- Name: users_users_roles_keys_bdd2fae7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_roles_keys_bdd2fae7 ON public.users USING btree (users_roles_keys);


--
-- Name: users_users_roles_keys_bdd2fae7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_roles_keys_bdd2fae7_like ON public.users USING btree (users_roles_keys varchar_pattern_ops);


--
-- Name: users_users_service_area_id_368f4595; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_service_area_id_368f4595 ON public.users USING btree (users_service_area_id);


--
-- Name: users_users_whatsapp_number_886070ea_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_users_whatsapp_number_886070ea_like ON public.users USING btree (users_whatsapp_number varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking_media booking_media_booking_media_bookin_c9f1d7d7_fk_bookings_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_media
    ADD CONSTRAINT booking_media_booking_media_bookin_c9f1d7d7_fk_bookings_ FOREIGN KEY (booking_media_bookings_id) REFERENCES public.bookings(bookings_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings bookings_bookings_car_cleaner_id_0ab62342_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_bookings_car_cleaner_id_0ab62342_fk_users_users_id FOREIGN KEY (bookings_car_cleaner_id) REFERENCES public.users(users_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings bookings_bookings_users_id_4df94e92_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_bookings_users_id_4df94e92_fk_users_users_id FOREIGN KEY (bookings_users_id) REFERENCES public.users(users_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_day_preferences customer_day_prefere_customer_day_prefere_100ce6d3_fk_plans_pla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_day_preferences
    ADD CONSTRAINT customer_day_prefere_customer_day_prefere_100ce6d3_fk_plans_pla FOREIGN KEY (customer_day_preferences_plans_id) REFERENCES public.plans(plans_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customer_day_preferences customer_day_prefere_customer_day_prefere_29d05c4b_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_day_preferences
    ADD CONSTRAINT customer_day_prefere_customer_day_prefere_29d05c4b_fk_users_use FOREIGN KEY (customer_day_preferences_users_id) REFERENCES public.users(users_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_plan_mapping_logs user_plan_mapping_lo_user_plan_mapping_lo_6cd3d78a_fk_user_plan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_plan_mapping_logs
    ADD CONSTRAINT user_plan_mapping_lo_user_plan_mapping_lo_6cd3d78a_fk_user_plan FOREIGN KEY (user_plan_mapping_logs_user_plan_mappings_id) REFERENCES public.user_plan_mappings(user_plan_mappings_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_plan_mapping_logs user_plan_mapping_lo_user_plan_mapping_lo_e47c2570_fk_plans_pla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_plan_mapping_logs
    ADD CONSTRAINT user_plan_mapping_lo_user_plan_mapping_lo_e47c2570_fk_plans_pla FOREIGN KEY (user_plan_mapping_logs_plans_id) REFERENCES public.plans(plans_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_plan_mappings user_plan_mappings_user_plan_mappings_p_bcaf51da_fk_plans_pla; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_plan_mappings
    ADD CONSTRAINT user_plan_mappings_user_plan_mappings_p_bcaf51da_fk_plans_pla FOREIGN KEY (user_plan_mappings_plans_id) REFERENCES public.plans(plans_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_plan_mappings user_plan_mappings_user_plan_mappings_u_5423ff41_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_plan_mappings
    ADD CONSTRAINT user_plan_mappings_user_plan_mappings_u_5423ff41_fk_users_use FOREIGN KEY (user_plan_mappings_users_id) REFERENCES public.users(users_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_users_preferred_cleaner_id_id_c96cecbc_fk_users_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_users_preferred_cleaner_id_id_c96cecbc_fk_users_users_id FOREIGN KEY (users_preferred_cleaner_id_id) REFERENCES public.users(users_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_users_roles_keys_bdd2fae7_fk_roles_roles_keys; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_users_roles_keys_bdd2fae7_fk_roles_roles_keys FOREIGN KEY (users_roles_keys) REFERENCES public.roles(roles_keys) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_users_service_area_i_368f4595_fk_service_a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_users_service_area_i_368f4595_fk_service_a FOREIGN KEY (users_service_area_id) REFERENCES public.service_areas(service_areas_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--